spring:
  application:
    name: SimpleFeign

server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@192.168.1.7:8761/eureka/,http://eureka:eureka@192.168.1.21:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.7
    
